### ISSUE TITLE
Use os.urandom instead of OS-specific implementation

### ISSUE THREAD

**Issue by mchubby** [KMHoodlet/Diceware#1]
See https://docs.python.org/3/library/os.html#os.urandom

You may want to keep existing code for Python 2 compatibility, though.

Edit: fixed typo

**Comment by KMHoodlet** [comment]
Thanks for the feedback! :smile: 

I've updated the functionality for random and SystemRandom seeding to utilize os.urandom. I haven't tested this specifically for Python 3, but I'm happy to take any further feedback you might have :grinning:
